# Generated by Django 3.2.14 on 2023-10-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('phone', models.CharField(max_length=150)),
                ('date_of_birth', models.CharField(max_length=150)),
                ('house_number', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=15)),
                ('street', models.CharField(max_length=15)),
                ('question', models.TextField(blank=True)),
                ('add_member', models.BooleanField(default=False)),
            ],
        ),
    ]
