# Generated by Django 3.2.14 on 2023-10-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='how_hear_about_us',
            field=models.CharField(choices=[('Via Internet', 'For Internet'), ('Outdour Ads', 'For Ads'), ('Family', 'For Via Family'), ('Friend and Neigbors', 'For Via Friend'), ('Social Media', 'For Social Media'), ('Internet Search Engine via Google', 'For Google'), ('Already Patient', 'For Already Patient'), ('Other', 'For Other')], default='Friend and Neigbors', max_length=50),
        ),
    ]
