# Generated by Django 3.2.14 on 2023-10-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_register_how_hear_about_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='street',
            field=models.CharField(max_length=200),
        ),
    ]
