# Generated by Django 3.2.14 on 2023-10-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_register_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('As a man', 'As A Man'), ('As a woman', 'As A Woman'), ('Like neither', 'Like Neither')], default='As a man', max_length=50),
        ),
    ]
