# Generated by Django 3.2.14 on 2023-10-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_register_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('As a man', 'Man'), ('As a woman', 'Woman'), ('Like neither', 'Like Neither')], default='As a man', max_length=50),
        ),
    ]
