# Generated by Django 3.2.14 on 2023-10-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_register_how_hear_about_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='register',
            name='house_number',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='register',
            name='how_hear_about_us',
            field=models.CharField(blank=True, choices=[('Via Internet', 'Internet'), ('Outdour Ads', 'Ads'), ('Family', 'Via Family'), ('Friend and Neigbors', 'Via Friend'), ('Social Media', 'Social Media'), ('Internet Search Engine via Google', 'Google'), ('Already Patient', 'Already Patient'), ('Other', 'Other')], default='Friend and Neigbors', max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='last_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='register',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='street',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='register',
            name='zipcode',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
