# Generated by Django 3.2.21 on 2023-10-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_register_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='add_member',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=50),
        ),
    ]
