# Generated by Django 3.2.21 on 2023-10-06 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_register_add_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='add_member',
            new_name='are_you_member',
        ),
    ]
